name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  GHCR: ghcr.io
  SNAPSHOT: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@bea6a01aa40b4d58b0382d47e1c4a70137af67b1
      with:
        buildkitd-flags: --debug
    
    - name: Login Github registry
      uses: docker/login-action@21f251affc0769ccac8a1cf17e937592fb492337
      with:
        registry: ${{ env.GHCR }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract Github image metadata
      id: gh-meta
      uses: docker/metadata-action@59bc9ddfd5a31eb6f5b55e89b65578fe3bbba85e
      with:
        images: ${{ env.GHCR }}/${{ env.SNAPSHOT }}
    
    - name: Snapshot build and push
      uses: docker/build-push-action@e27bcee4eb9e7b4bc168418e3364c4482120393a
      with:
        push: true
        tags: ${{ steps.gh-meta.outputs.tags }}
        labels: ${{ steps.gh-meta.outputs.labels }}
